project:
  type: manuscript
  execute-dir: project
  output-dir: docs

manuscript:
  article: index.qmd
  notebooks:
    - notebook: notebooks/mlr3.qmd
      title: "Prediction Analysis"
    - notebook: notebooks/hypothethis-tests.qmd
      title: "Hypothesis Testing"
    - notebook: notebooks/RL-via-HM.qmd
      title: "Predict RL via HM"
  code-links:
    - text: Code of data preparation
      icon: file-code
      href: R/data_prep.R
  resources:
    - R/data_prep.R

format:
  html:
    toc-depth: 4
    include-in-header:
      - text: "<style>.quarto-notebook .cell-container .cell-decorator { display: none; }</style>"
  docx: default
  pdf: default
  # jats: default
execute:
  freeze: auto
  warning: false
  message: false
  error: false


