project:
  type: manuscript
  execute-dir: project
  output-dir: docs

manuscript:
  article: index.qmd
  notebooks:
    - notebook: notebooks/mlr3.qmd
      title: "Prediction Analysis"
    - notebook: notebooks/hypothethis-tests.qmd
      title: "Hypothesis Testing"
  code-links:
    - text: Code of data preparation
      icon: file-code
      href: R/data_prep.R
  # resources:
  #   - data/cars.csv

format:
  docx: default
  jats: default
  pdf: default
  html:
    toc-depth: 4
    comments:
      hypothesis: true
execute:
  freeze: auto


