project:
  type: manuscript
  execute-dir: project
  output-dir: docs

manuscript:
  article: index.qmd
  # notebooks:
  #   - notebook: notebooks/cars-plot.qmd
  #     title: CarsPlot
  code-links:
    - text: Code of prelimary analysis
      icon: file-code
      href: R/analysis.R
  # resources:
  #   - data/cars.csv

format:
  html:
    comments:
      hypothesis: true
    # other-links:
    #   - text: NASA Open Data
    #     href: https://data.nasa.gov/
  docx: default
  jats: default
  pdf: default

# execute:
#   freeze: true



